### ISSUE TITLE
unannotated figure

### ISSUE THREAD

**Issue by vick2075** [b96young/online-ballistic-calculator#1]
Hi,

With regard to line 108 in ballistic-calculator.py:

ax = -1/8 * Cdref / BC * pi * airDensity * (vxinitial-wx)**2

What is 1/8 for? And why is pi in this equation?

**Comment by b96young** [comment]
It is a factored version of the aerodynamic drag equation:

We first need to rearrange the BC equation so that we get the actual Cd value:

Cdactual = (m / d^2) * (Cdref / BC)

Now we can substitute this equation into the drag equation from earlier:

a = 1/2 * Cd * Aref * rho * v^2 / m

a = 1/2 * (m / d^2) * (Cdref / BC) * Aref * rho * v^2 / m

If we recognize that the formula for area is: A = pi * r^2

d = 2 * r

A = pi * (d / 2)^2

A = pi * d^2 / 4

The formula then becomes:

a = 1/2 * (m / d^2) * (Cdref / BC) * pi * d^2 / 4 * rho * v^2 / m

You will notice that the mass (m) and diameter (d²) cancel out:

a = 1/2  * (Cdref / BC) * pi / 4 * rho * v^2

Our final equation simplifies to this:

a = 1/8 * PI * Cdref / BC * rho * v^2

**Comment by vick2075** [comment]
Good explanation. Thanks a lot!
